name: e2e

on:
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Docker runtime setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: ./docker/Dockerfile
          tags: kintone-mcp-server:e2e
          load: true
        env:
          DOCKER_BUILD_SUMMARY: false

      # Node.js setup
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # NPX runtime setup
      - name: Install @kintone/mcp-server globally
        run: |
          pnpm build
          npm install -g .

      # Proxy setup
      - name: Start Squid proxy (no auth)
        run: |
          docker run -d \
            --name squid \
            -p 3128:3128 \
            -v ${{ github.workspace }}/docker/squid.conf:/etc/squid/squid.conf \
            ubuntu/squid:latest

      - name: Start Squid proxy (with auth)
        run: |
          docker run -d \
            --name squid \
            -p 3129:3128 \
            -v ${{ github.workspace }}/docker/squid-auth.conf:/etc/squid/squid.conf \
            -v ${{ github.workspace }}/docker/passwords:/etc/squid/passwords \
            ubuntu/squid:latest

      # E2E test execution
      - name: Run E2E tests
        env:
          KINTONE_BASE_URL: ${{ secrets.E2E_KINTONE_BASE_URL }}
          KINTONE_USERNAME: ${{ secrets.E2E_KINTONE_USERNAME }}
          KINTONE_PASSWORD: ${{ secrets.E2E_KINTONE_PASSWORD}}
          KINTONE_API_TOKEN: ${{ secrets.E2E_API_TOKEN}}
          KINTONE_BASIC_AUTH_USERNAME: ${{ secrets.E2E_BASIC_AUTH_USERNAME }}
          KINTONE_BASIC_AUTH_PASSWORD: ${{ secrets.E2E_BASIC_AUTH_PASSWORD }}
          KINTONE_PFX_FILE_PATH: ${{ secrets.E2E_PFX_FILE_PATH }}
          KINTONE_PFX_PASSWORD: ${{ secrets.E2E_PFX_PASSWORD }}
          KINTONE_PROXY_URL: http://localhost:3128
          KINTONE_AUTH_PROXY_URL: http://localhost:3129
          KINTONE_AUTH_PROXY_USERNAME: testuser
          KINTONE_AUTH_PROXY_PASSWORD: testpass

        run: |
          echo "Running E2E tests"
